export interface Personality {
    travel_destination: string,
    start_day: string,
    finish_day: string,
    travel_day: number,
    rank_mountain: number,
    rank_sea: number,
    rank_historicalTheme: number,
    rank_experienceTheme: number,
    rank_buildingTheme: number,
    rank_cafe: number,
    rank_koreanfood: number,
    rank_japanesefood: number,
    rank_chinesefood: number,
    rank_westernfood: number,
    rank_fastfood: number,
    rank_meat: number,
    rank_hotel: number,
    rank_motel: number,
    rank_pension: number,
}